# Generated by Django 5.2 on 2025-04-29 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='Номер класса')),
                ('main_cabinet', models.IntegerField(verbose_name='Номер кабинета')),
                ('school_number', models.IntegerField(verbose_name='Номер школы')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('height', models.IntegerField(verbose_name='Рост, в см')),
                ('weight', models.IntegerField(verbose_name='Вес, в кг')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='laba.studentclass')),
            ],
        ),
    ]
